domain: corinna.ghaznavi.org
url: https://corinna.ghaznavi.org
baseurl: "/"

title: Corinna Ghaznavi
email: corinna.ghaznavi@gmail.com
author: Corinna Ghaznavi

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "corinna.ghaznavi@gmail.com"
